-- Baltazar Customs — popular a coleção com as pranchas que já estão no repositório
-- As imagens já estão publicadas no Vercel em /images/... (não precisa subir nada).
-- Rode UMA vez no SQL editor do Supabase. Idempotente: apaga o seed antigo e recria.
-- (Novas pranchas que o César adicionar pelo /admin NÃO são afetadas — elas usam
--  image_path do bucket, não começam com '/'.)

delete from public.boards where image_path like '/images/%';

insert into public.boards (image_path, category_slug, fin_setup, line, sort_order, active) values
  ('/images/IMG_6839.jpeg', 'twin', 'Twin', null, 0, true),
  ('/images/IMG_6846.jpeg', 'thruster', 'Thruster', null, 1, true),
  ('/images/IMG_6845.jpeg', 'longboard', 'Single', null, 2, true),
  ('/images/IMG_6873.jpeg', 'twin', 'Twin', null, 3, true),
  ('/images/IMG_6857.jpeg', 'mid-length', 'Single + Estab.', null, 4, true),
  ('/images/IMG_6880.jpeg', 'quad', 'Quad', null, 5, true),
  ('/images/IMG_6837.jpeg', 'twin', 'Twin Keel', null, 6, true),
  ('/images/IMG_6853.jpeg', 'thruster', 'Thruster', null, 7, true),
  ('/images/IMG_6844.jpeg', 'twin', 'Twin', null, 8, true),
  ('/images/IMG_6868.jpeg', 'twin', 'Twin', null, 9, true),
  ('/images/IMG_6876.jpeg', 'thruster', 'Thruster', null, 10, true),
  ('/images/IMG_6883.jpeg', 'twin', 'Twin', null, 11, true),
  ('/images/IMG_6858.jpeg', 'thruster', '5 Caixas', null, 12, true),
  ('/images/IMG_6852.jpeg', 'twin', 'Twin Keel', null, 13, true),
  ('/images/IMG_6865.jpeg', 'quad', 'Quad', null, 14, true),
  ('/images/IMG_6841.jpeg', 'twin', 'Twin', null, 15, true),
  ('/images/IMG_6849.jpeg', 'thruster', 'Thruster', null, 16, true),
  ('/images/IMG_6835.jpeg', 'twin', 'Twin', 'Carbon Trash', 17, true),
  ('/images/IMG_6884.jpeg', 'twin', 'Twin', null, 18, true),
  ('/images/IMG_6856.jpeg', 'twin', 'Twin', 'Carbon Trash', 19, true),
  ('/images/IMG_6874.jpeg', 'thruster', 'Thruster', null, 20, true),
  ('/images/IMG_6875.jpeg', 'twin', 'Twin', null, 21, true),
  ('/images/IMG_6832.jpeg', 'twin', 'Twin', null, 22, true),
  ('/images/IMG_6836.jpeg', 'twin', 'Twin', 'Carbon Trash', 23, true),
  ('/images/IMG_6838.jpeg', 'twin', 'Twin', null, 24, true),
  ('/images/IMG_6840.jpeg', 'twin', 'Twin', 'Carbon Trash', 25, true),
  ('/images/IMG_6847.jpeg', 'twin', 'Twin', null, 26, true),
  ('/images/IMG_6848.jpeg', 'twin', 'Twin', 'Carbon Trash', 27, true),
  ('/images/IMG_6855.jpeg', 'twin', 'Twin', 'Carbon Trash', 28, true),
  ('/images/IMG_6859.jpeg', 'twin', 'Twin', null, 29, true),
  ('/images/IMG_6872.jpeg', 'twin', 'Twin', null, 30, true),
  ('/images/IMG_6885.jpeg', 'twin', 'Twin', null, 31, true),
  ('/images/baltazar/baltz-001.jpeg', 'outras', 'Variável', null, 32, true),
  ('/images/baltazar/baltz-002.jpeg', 'twin', 'Twin', null, 33, true),
  ('/images/baltazar/baltz-003.jpeg', 'thruster', 'Thruster', null, 34, true),
  ('/images/baltazar/baltz-004.jpeg', 'mid-length', 'Single + Estab.', null, 35, true),
  ('/images/baltazar/baltz-005.jpeg', 'longboard', 'Single', null, 36, true),
  ('/images/baltazar/baltz-006.jpeg', 'mid-length', 'Single + Estab.', null, 37, true),
  ('/images/baltazar/baltz-007.jpeg', 'twin', 'Twin', null, 38, true),
  ('/images/baltazar/baltz-008.jpeg', 'quad', 'Quad', null, 39, true),
  ('/images/baltazar/baltz-009.jpeg', 'twin', 'Twin', null, 40, true),
  ('/images/baltazar/baltz-010.jpeg', 'twin', 'Twin', null, 41, true),
  ('/images/baltazar/baltz-011.jpeg', 'twin', 'Twin Keel', null, 42, true),
  ('/images/baltazar/baltz-012.jpeg', 'twin', 'Twin', null, 43, true),
  ('/images/baltazar/baltz-013.jpeg', 'thruster', 'Thruster', null, 44, true),
  ('/images/baltazar/baltz-014.jpeg', 'longboard', 'Single', null, 45, true),
  ('/images/baltazar/baltz-015.jpeg', 'mid-length', 'Single + Estab.', null, 46, true),
  ('/images/baltazar/baltz-016.jpeg', 'twin-plus-1', 'Twin + Estab.', null, 47, true),
  ('/images/baltazar/baltz-017.jpeg', 'longboard', 'Single', null, 48, true),
  ('/images/baltazar/baltz-018.jpeg', 'mid-length', 'Single + Estab.', null, 49, true),
  ('/images/baltazar/baltz-019.jpeg', 'twin', 'Twin', null, 50, true),
  ('/images/baltazar/baltz-020.jpeg', 'mid-length', 'Single + Estab.', null, 51, true),
  ('/images/baltazar/baltz-021.jpeg', 'longboard', 'Single', null, 52, true),
  ('/images/baltazar/baltz-022.jpeg', 'twin', 'Twin', null, 53, true),
  ('/images/baltazar/baltz-023.jpeg', 'twin', 'Twin', null, 54, true),
  ('/images/baltazar/baltz-024.jpeg', 'outras', 'Variável', null, 55, true),
  ('/images/baltazar/baltz-025.jpeg', 'thruster', 'Thruster', null, 56, true);
